name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  otp_version: 26.1.2
  elixir_version: 1.16.1
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp_version }}
          elixir-version: ${{ env.elixir_version }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: deps_cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-test-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-test-
          save-always: true
      - name: Install dependencies
        if: steps.deps_cache.outputs.cache-hit != 'true'
        run: mix deps.get --only test
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-test-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-build-test-
          save-always: true
      - name: Build
        env:
          MIX_ENV: test
        run: mix compile
      - name: Run tests
        run: mix test
  build-dev:
    name: Build dev
    runs-on: ubuntu-latest
    steps:
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp_version }}
          elixir-version: ${{ env.elixir_version }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: deps_cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-dev-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-dev-
          save-always: true
      - name: Install dependencies
        if: steps.deps_cache.outputs.cache-hit != 'true'
        run: mix deps.get --only dev
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-build-dev-
          save-always: true
      - name: Build
        env:
          MIX_ENV: dev
        run: mix compile
  credo:
    name: Credo
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp_version }}
          elixir-version: ${{ env.elixir_version }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Restore dependencies from cache
        uses: actions/cache/restore@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Restore build from cache
        uses: actions/cache/restore@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Run credo checks
        run: mix credo --strict
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp_version }}
          elixir-version: ${{ env.elixir_version }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Restore dependencies from cache
        uses: actions/cache/restore@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Restore build from cache
        uses: actions/cache/restore@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Check formatted
        run: mix format --check-formatted
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Install Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp_version }}
          elixir-version: ${{ env.elixir_version }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Restore dependencies from cache
        uses: actions/cache/restore@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Restore build from cache
        uses: actions/cache/restore@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-${{ hashFiles('mix.lock') }}
          fail-on-cache-miss: true
      - name: Cache PLTs
        id: plt_cache
        uses: actions/cache@v4
        with:
          path: priv/plt
          key: ${{ runner.os }}-plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
          save-always: true
      - name: Build PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Run dialyzer
        run: mix dialyzer --format github
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - credo
      - dialyzer
      - formatter
      - test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency: deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.12
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
